### PR TITLE
Min/MaxLength attributes relay added

### LINKED ISSUE #678: Feature: Create a string specimen with Min/MaxLength constraint
The following two tests fail:

``` csharp
[Theory, AutoData]
public void CreateParameterWithMinLengthConstraint([MinLength(5)]string p)
{
    Assert.True(p.Length == 5); // fails; actual is 37
}

[Theory, AutoData]
public void CreateParameterWithMaxLengthConstraint([MaxLength(5)]string p)
{
    Assert.True(p.Length == 5); // fails; actual is 37
}
```

In order to make it pass two new _relays_ similar to [StringLengthAttributeRelay](https://github.com/AutoFixture/AutoFixture/blob/master/Src/AutoFixture/DataAnnotations/StringLengthAttributeRelay.cs) need to be implemented.

**Important:** the [MaxLengthAttribute](https://msdn.microsoft.com/en-us/library/system.componentmodel.dataannotations.maxlengthattribute%28v=vs.110%29.aspx) and [MinLengthAttribute](https://msdn.microsoft.com/en-us/library/system.componentmodel.dataannotations.minlengthattribute%28v=vs.110%29.aspx) classes are available since .Net 4.5 so those AutoFixture projects that are still on .Net 4.0 have to be upgraded (that should cause no problems since 4.5 is [backward compatible](https://blogs.msdn.microsoft.com/dotnet/2011/09/26/compatibility-of-net-framework-4-5/) with 4.0).

### PR DESCRIPTION
**Pull request by damian-krychowski**
Hi guys, 

I have implemented MinAndMaxLenghtAttributeRelay (I created that based on StringLengthAttributeRelay). I have decided to create one relay for both Min and Max attributes to be able to handle a situation when both of them are applied to a single property at once. 

All remarks will be highly appreciated! 

Closes #678

### CODE REVIEW

File: Src/AutoFixture/DataAnnotations/MinAndMaxLengthAttributeRelay.cs [hunk 1]
```diff
@@ -0,0 +1,48 @@
...
+
+            if (maxLengthAttribute == null && minLengthAttribute == null)
+            {
+                return new NoSpecimen();
+            }
+
+            var minLength = minLengthAttribute?.Length ?? 0;
+            var maxLength = maxLengthAttribute?.Length ?? Int32.MaxValue;
+
+            return context.Resolve(new ConstrainedStringRequest(minLength, maxLength));
```
Comment (zvirja) [inline Src/AutoFixture/DataAnnotations/MinAndMaxLengthAttributeRelay.cs]: According to the [MSDN](https://msdn.microsoft.com/en-us/library/system.componentmodel.dataannotations.maxlengthattribute(v=vs.110).aspx) this attribute can control both string and array length. Therefore, we should check the member type and if that is an array, we should create `FiniteSequenceRequest`.

File: Src/AutoFixture/DataAnnotations/MinAndMaxLengthAttributeRelay.cs [hunk 2]
```diff
@@ -31,18 +41,117 @@ public object Create(object request, ISpecimenContext context)
...
+        {
+            return context.Resolve(new RangedNumberRequest(typeof(int), range.Min, range.Max));
+        }
+
+        private static object GetRandomCollection(ISpecimenContext context, Type elementType, object collectionCount)
+        {
+            return context.Resolve(new FiniteSequenceRequest(elementType, (int)collectionCount));
+        }
+
+        private static object ToArray(IEnumerable elements, Type elementType)
```
Comment (damian-krychowski) [inline Src/AutoFixture/DataAnnotations/MinAndMaxLengthAttributeRelay.cs]: This function was copied from ArrayRelay. I would prefer to unify this logic somehow - @zvirja maybe some extension method for IEnumerable type? Or maybe you have some other suggestions?

File: Src/AutoFixture/DataAnnotations/IMemberTypeResolver.cs [hunk 3]
```diff
@@ -0,0 +1,9 @@
+﻿using System;
+
+namespace AutoFixture.DataAnnotations
+{
+    public interface IMemberTypeResolver
```
Comment (damian-krychowski) [inline Src/AutoFixture/DataAnnotations/IMemberTypeResolver.cs]: @zvirja I had to introduce this interface to be able to test the Relay - but I found it is something that was not practiced before - injecting dependencies into the relays. Unfortunately, type FakeMamberInfo does not provide a way to mock a MemberType, and I am not sure if that is even possible for it to do. Maybe you can figure out a better way to achieve this testability without introducing this interface?

**Comment by damian-krychowski** [comment]
Hi @zvirja, will you find some time to review the changes?

File: Src/AutoFixture/DataAnnotations/MinAndMaxLengthAttributeRelay.cs [hunk 4]
```diff
@@ -0,0 +1,161 @@
...
+    /// </summary>
+    public class MinAndMaxLengthAttributeRelay : ISpecimenBuilder
+    {
+        private readonly IMemberTypeResolver memberTypeResolver;
+
+        /// <summary>
+        /// Creates a new instance of MinAndMaxLengthAttributeRelay
+        /// </summary>
+        /// <param name="memberTypeResolver">MemberTypeResolver to determine member type of requested object</param>
+        public MinAndMaxLengthAttributeRelay(IMemberTypeResolver memberTypeResolver)
```
Comment (zvirja) [inline Src/AutoFixture/DataAnnotations/MinAndMaxLengthAttributeRelay.cs]: Please use property injection here instead of constructor injection. We have a good default for the `IMemberTypeResolver`, so no need for client to pass it.

Example:
https://github.com/AutoFixture/AutoFixture/blob/11066d77bcee17e4175679cfa0e9133957695671/Src/AutoFixture.NUnit3/AutoDataAttribute.cs#L27-L31

File: Src/AutoFixture/DataAnnotations/MinAndMaxLengthAttributeRelay.cs [hunk 5]
```diff
@@ -0,0 +1,161 @@
...
+            }
+
+            var range = Range.TryGetFromAttributes(request);
+            
+            if (range == null)
+            {
+                return new NoSpecimen();
+            }
+
+            var memberType = memberTypeResolver.TryGetMemberType(request);
```
Comment (zvirja) [inline Src/AutoFixture/DataAnnotations/MinAndMaxLengthAttributeRelay.cs]: Please update also [`RangeAttributeRelay`](https://github.com/AutoFixture/AutoFixture/blob/11066d77bcee17e4175679cfa0e9133957695671/Src/AutoFixture/DataAnnotations/RangeAttributeRelay.cs#L52) to use this interface. Use property injection pattern there as well.

Implementation might look like following:
```c#
private static Type GetMemberType(RangeAttribute rangeAttribute, object request)
{
    if (this.MemberTypeResolver.TryGetMemberType(request, out var memberType))
    {
        return memberType;
    }

    return Nullable.GetUnderlyingType(rangeAttribute.OperandType) ?? rangeAttribute.OperandType;
}
```

File: Src/AutoFixture/DataAnnotations/MinAndMaxLengthAttributeRelay.cs (hunk 2 above)
Comment (zvirja) [reply Src/AutoFixture/DataAnnotations/MinAndMaxLengthAttributeRelay.cs]: Let's keep that as is for now 😉 Usually we try to follow the rule of 3 and unify it only in that case. For now it's unclear what is the best way to do that. The idea with extension method would probably work as well, but let's postpone it for now.

File: Src/AutoFixture/DataAnnotations/MinAndMaxLengthAttributeRelay.cs [hunk 6]
```diff
@@ -0,0 +1,161 @@
...
+                    ? null
+                    : GetRange(minLengthAttribute, maxLengthAttribute);
+            }
+
+            private static Range GetRange(MinLengthAttribute minLengthAttribute, MaxLengthAttribute maxLengthAttribute)
+            {
+                var min = minLengthAttribute?.Length ?? 0;
+                var max = maxLengthAttribute?.Length ?? Int32.MaxValue;
+
+                //to avoid creation of empty strings/arrays
```
Comment (zvirja) [inline Src/AutoFixture/DataAnnotations/MinAndMaxLengthAttributeRelay.cs]: Styling. Change to `// To avoid creation of empty strings/arrays.`

File: Src/AutoFixture/DataAnnotations/MinAndMaxLengthAttributeRelay.cs [hunk 7]
```diff
@@ -0,0 +1,161 @@
...
+
+            if (collectionCount is NoSpecimen)
+                return new NoSpecimen();
+
+            var resultCollection = GetRandomCollection(context, elementType, collectionCount);
+
+            return ToArray((IEnumerable)resultCollection, elementType);
+        }
+
+        private static object GetRandomNumberWithinRange(ISpecimenContext context, Range range)
```
Comment (zvirja) [inline Src/AutoFixture/DataAnnotations/MinAndMaxLengthAttributeRelay.cs]: Change signature to return `int` as only this method knows the type of result.

File: Src/AutoFixtureUnitTest/DataAnnotations/MinAndMaxLengthAttributeRelayTest.cs [hunk 8]
```diff
@@ -0,0 +1,273 @@
...
+            sut.Create(request, context);
+
+            //Assert
+            var expectedRequest = new ConstrainedStringRequest(expectedMin, max);
+
+            Assert.Equal(expectedRequest, actualRequest);
+
+        }
+
+        private class MockMemberTypeResolver : IMemberTypeResolver
```
Comment (zvirja) [inline Src/AutoFixtureUnitTest/DataAnnotations/MinAndMaxLengthAttributeRelayTest.cs]: Please create `DelegatingMemberTypeResolver` like [this](https://github.com/AutoFixture/AutoFixture/blob/11066d77bcee17e4175679cfa0e9133957695671/Src/AutoFixtureUnitTest/Kernel/DelegatingSpecimenContext.cs#L6) and return `false` by default. I'd expect that each test would configure it rather than relying on default behavior - for better readability.

File: Src/AutoFixture/DataAnnotations/MinAndMaxLengthAttributeMemberTypeResolver.cs [hunk 9]
```diff
@@ -0,0 +1,46 @@
+﻿using System;
+using System.Reflection;
+
+namespace AutoFixture.DataAnnotations
+{
+    /// <summary>
+    /// Member type resolver used by MinAndMaxLengthAttributeRelay
+    /// </summary>
+    public class MinAndMaxLengthAttributeMemberTypeResolver : IMemberTypeResolver
```
Comment (zvirja) [inline Src/AutoFixture/DataAnnotations/MinAndMaxLengthAttributeMemberTypeResolver.cs]: Please add unit tests for this class.

File: Src/AutoFixture/DataAnnotations/MinAndMaxLengthAttributeRelay.cs [hunk 10]
```diff
@@ -0,0 +1,161 @@
...
+        {
+            return memberType?.IsArray ?? false;
+        }
+        
+       private static object ResolveString(ISpecimenContext context, Range range)
+        {
+            return context.Resolve(new ConstrainedStringRequest(range.Min, range.Max));
+        }
+
+        private static object ResolveArray(ISpecimenContext context, Type memberType, Range range)
```
Comment (zvirja) [inline Src/AutoFixture/DataAnnotations/MinAndMaxLengthAttributeRelay.cs]: Probably it makes sense to rename `memberType` to `arrayType` 😉

File: Src/AutoFixture/DataAnnotations/MinAndMaxLengthAttributeRelay.cs [hunk 11]
```diff
@@ -0,0 +1,161 @@
...
+        {
+            var elementType = memberType.GetElementType();
+
+            var collectionCount = GetRandomNumberWithinRange(context, range);
+
+            if (collectionCount is NoSpecimen)
+                return new NoSpecimen();
+
+            var resultCollection = GetRandomCollection(context, elementType, collectionCount);
```
Comment (zvirja) [inline Src/AutoFixture/DataAnnotations/MinAndMaxLengthAttributeRelay.cs]: Should we test against `NoSpecimen` reply here?

**Comment by zvirja** [comment]
@damian-krychowski Thanks a lot for the follow-up! I've added a few minor tweaks to the code.

@moodmosaic Do you want to take a look as well? 😉

**Comment by zvirja** [comment]
@moodmosaic Thanks for the quick check 😉 
@damian-krychowski I've merged the PR. Thanks for all your efforts and sorry for the belonged replies 🙏 🍷
