### PR TITLE
Proposed fix for #1183 - multiple regex within short time might give identical strings

### LINKED ISSUE #1183: Creating multiple regular expression requests in rapid succession yields same result (.NET framework)
The test below (usually) fails in .NET framework fails in .NET framework, but not in core.

The underlying reason for this is that Xeger is used in autofixture without injecting an object of type Random, and Xeger uses `new Random()` - without injecting a seed.

The test passes, in .NET Core, because `new Random()` internally generates a unique seed.
However, as you probably know, in framework, it uses tick count as seed.

I haven't created a pr, because I didn't know where to do it to - does it make sense to create a pr with a failing test to master?

And I don't know if it should be fixed here in AF, or a pr should be created in the Fare repo.

What do you think? I'd like to fix this - but I'm not sure how to proceed...

```
        [Theory]
        [InlineData(@"^[A-Z]{27}$")]
        public void CreateTwoWithRegularExpressionRequestReturnsDifferentResults(string pattern)
        {
            // Arrange
            var sut = new RegularExpressionGenerator();
            
            var request = new RegularExpressionRequest(pattern);
            var dummyContext = new DelegatingSpecimenContext();
            // Act
            var result1 = sut.Create(request, dummyContext);
            var result2 = sut.Create(request, dummyContext);
            
            // Assert
            Assert.NotEqual(result1, result2);
        }
```

### PR DESCRIPTION
**Pull request by MagnusMikkelsen**
Included:
- Test that exposes the issue
- Proposed fix:
    - Use `Xeger(pattern, random)` constructor overload
    - Use the same instance of `Random` each time. I figured it should be enough to avoid the issue with identical seeds.

Fix #1183

### CODE REVIEW

File: Src/AutoFixtureUnitTest/RegularExpressionGeneratorTest.cs [hunk 1]
```diff
@@ -103,6 +103,31 @@ public void CreateWithRegularExpressionRequestReturnsCorrectResult(string patter
...
+            // Xeger(pattern) internally creates an instance of Random with the default seed.
+            // This means that the RegularExpressionGenerator might create identical strings
+            // if called multiple times within a short time.
+
+            // Arrange
+            var sut = new RegularExpressionGenerator();
+            var request = new RegularExpressionRequest(pattern);
+            var dummyContext = new DelegatingSpecimenContext();
+
+            // Repeat a few times - because the issue seen comes from Random class using tickcount as seed.
```
Comment (moodmosaic) [inline Src/AutoFixtureUnitTest/RegularExpressionGeneratorTest.cs:120]:
```suggestion
            // Repeat a few times to make the test more robust.
```

File: Src/AutoFixtureUnitTest/RegularExpressionGeneratorTest.cs [hunk 2]
```diff
@@ -103,6 +103,31 @@ public void CreateWithRegularExpressionRequestReturnsCorrectResult(string patter
...
+            for (int i = 0; i < 10; i++)
+            {
+                var result1 = sut.Create(request, dummyContext);
+                var result2 = sut.Create(request, dummyContext);
+
+                // Assert
+                Assert.NotEqual(result1, result2);
```
Comment (moodmosaic) [inline Src/AutoFixtureUnitTest/RegularExpressionGeneratorTest.cs:127]: Wouldn't it be possible to avoid the `for-loop` and the [Assertion Roulette](http://xunitpatterns.com/Assertion%20Roulette.html) by doing something similar to what you did [here](https://github.com/moodmosaic/Fare/pull/56/commits/1563f8e5cea71bb58c85e7843498796d81975715#diff-a4691edefa1cec0b62875a993b25ed7c)? 👀

File: Src/AutoFixture/RegularExpressionGenerator.cs [hunk 3]
```diff
@@ -10,6 +10,16 @@ namespace AutoFixture
...
     public class RegularExpressionGenerator : ISpecimenBuilder
     {
+        private readonly Random random;
+
+        /// <summary>
+        /// Initializes a new instance of the <see cref="RegularExpressionGenerator"/> class.
+        /// </summary>
+        public RegularExpressionGenerator()
+        {
+            this.random = new Random();
```
Comment (moodmosaic) [inline Src/AutoFixture/RegularExpressionGenerator.cs:20]: This looks reasonable *if* RegularExpressionGenerator has also the same, transient, scope.

(A test similar to [this](https://github.com/moodmosaic/Fare/pull/56/commits/1563f8e5cea71bb58c85e7843498796d81975715#diff-a4691edefa1cec0b62875a993b25ed7c) one, which you did previously, should give the answer.)

File: Src/AutoFixtureUnitTest/RegularExpressionGeneratorTest.cs (hunk 2 above)
Comment (MagnusMikkelsen) [reply Src/AutoFixtureUnitTest/RegularExpressionGeneratorTest.cs:127]: Yes - totally, just didn't know if introducing linq in this test was acceptable? Commit on the way.

File: Src/AutoFixture/RegularExpressionGenerator.cs (hunk 3 above)
Comment (MagnusMikkelsen) [reply Src/AutoFixture/RegularExpressionGenerator.cs:20]: ok - I've added a test in FixtureTests.

File: Src/AutoFixture/RegularExpressionGenerator.cs [hunk 4]
```diff
@@ -28,16 +38,18 @@ public object Create(object request, ISpecimenContext context)
...
+        private object GenerateRegularExpression(RegularExpressionRequest request)
         {
             string pattern = request.Pattern;
 
             try
             {
-                string regex = new Xeger(pattern).Generate();
+                // Use the Xeger constructor overload that that takes an instance of Random.
+                // Otherwise identically strings can be generated, if regex are generated within short time.
+                string regex = new Xeger(pattern, this.random).Generate();
```
Comment (zvirja) [inline Src/AutoFixture/RegularExpressionGenerator.cs:52]: As per my knowledge `Random` is not thread safe. See e.g. [here](https://stackoverflow.com/a/3049478/2009373). Previously we created a random instance per request (probably internally within Xeger), so we didn't have that problem.

Fixture by design can be used from multiple threads simultaneously, so we should take care of multi-threading.

Comment (MagnusMikkelsen) [reply Src/AutoFixture/RegularExpressionGenerator.cs:52]: Ok, I'll look into it.
Should we use the code from https://codeblog.jonskeet.uk/2009/11/04/revisiting-randomness/ ? 

Basically doing `Xeger(pattern, ThreadLocalRandom.Instance)`

This way we could abstract threadsafety concerns out of RegularExpressionGenerator... 🤔, and maybe reuse it elsewhere.

Comment (moodmosaic) [reply Src/AutoFixture/RegularExpressionGenerator.cs:52]: @MagnusMikkelsen you can just follow the pattern used in all the other generators, e.g.

https://github.com/AutoFixture/AutoFixture/blob/d3e14a818b933d948ea82464b197a5aeb152f070/Src/AutoFixture/RandomNumericSequenceGenerator.cs#L144

Comment (zvirja) [reply Src/AutoFixture/RegularExpressionGenerator.cs:52]: @moodmosaic @MagnusMikkelsen If there is any way to do that without locks, please prefer that way. Introducing locking makes it hard to optimize performance later. When you have a bit suite, AutoFixture already takes substantial amount of time due to uncached reflection is uses everywhere - we shouldn't degrade it even more 😟 

In this particular case, it might be better to abstract out random generation and create generator, which uses e.g. `Interlocked`. Or, for instance, create thread-local random, but use interlocked to generate seed.

Comment (moodmosaic) [reply Src/AutoFixture/RegularExpressionGenerator.cs:52]: Interlocked.CompareExchange or (IIRC) the Interlocked-extras by Jeffrey Richter in _CLR via C#_ can be candidates. 

- Unless you measure it, you can’t actually know how much ‘faster’ it’s going to be
- If speed matters, perhaps we can consider #928 — or [look into other PRNGs](https://github.com/AutoFixture/AutoFixture/issues/1040)

Though right now, I’d suggest we stick with `lock` as done in all other places and be consistent.

Comment (MagnusMikkelsen) [reply Src/AutoFixture/RegularExpressionGenerator.cs:52]: Not sure how to use Interlocked.CompareExchange for this?

I did a couple of measurements, running the test below.
The times are measured using dotTrace, and are the total time and own time for `RegularExpressionGenerator.GenerateRegularExpression`.
The last test (ThreadLocal) took 12s. Seems to make sense, given the `GenerateRegularExpression` used some 85 seconds in total on 8 threads.

|					|Total Time [ms]  |	Own  [ms] |
|---------------------------|------------------|--------------|
|Current: shared `Random`|  83387               |  0                |
|Original: No injected `Random` | 88926 |	10 |
|New `Random` each time<br>locking on generate seed | 100843 |	0 |
| Sharing `ThreadLocal` <br> locking when generating `ThreadLocal` | 84848 |	27 |

(It is beside the point of this PR - but the `Xeger.ctor` seems to take most of this time - 81000ms total time. `Generate` is about 550ms total time. Might be an idea to cache `Xeger`? Fx `dictionary[pattern]=Xeger`)

``` cs
        [Fact]
        public void CreateManyAnonymousInParallelWithRegularExpressionValidatedTypeReturnsCorrectResult()
        {
            // Arrange
            var fixture = new Fixture();
            var result = Enumerable
                .Range(0, 10000)
                .AsParallel()
                .WithDegreeOfParallelism(8)
                .Select(_ => fixture.Create<RegularExpressionValidatedType>())
                .ToArray();

            // Assert

            Assert.All(result, r => Assert.Matches(RegularExpressionValidatedType.Pattern, r.Property));
            Assert.Equal(result.Distinct(), result);
        }
```

Comment (MagnusMikkelsen) [reply Src/AutoFixture/RegularExpressionGenerator.cs:52]: > Interlocked-extras by Jeffrey Richter in _CLR via C#_ can be candidates.
Haven't got that book - so I don't it, do you have any links with examples? I'd like to learn new tricks 😁

**Comment by MagnusMikkelsen** [comment]
> @MagnusMikkelsen, thank you for the investigation 👍 

You're welcome - I'm having fun 😁

>  just use `lock` and plan for perf improvements separately when needed.

I think I agree. In case there are many scenarios out there, that uses the same instance of Fixture to generate the same patterns many times - a major improvement would be to cache Xeger - much greater than those 2ms we gain by sharing the `Random`.

Just ran a small experiment in linqpad. Creating 1000 `Xeger` and generating regex takes 2 seconds. Reusing a `Xeger` to generate 1000 regex took ca 40ms.

**Comment by zvirja** [comment]
@MagnusMikkelsen Thanks for the rework and fixing the concurrency issue. I fully agree that now we can proceed further with the current approach and merge the code. You are guarding by lock only random seed generation, so it sounds reasonable. My concern was about protecting the whole `Create()` method.

Just in case you are curious, my idea was to have something like:

```c#
static private int RandomSeed = Environment.TickCount;
...

new Xeger(new Random(Interlocked.Add(ref RandomSeed, 1)))

```

This way code is completely lock-free and you are always giving a new seed to random. I believe in this case it doesn't matter whether we just increment seed by one, or use completely random input - the `Random` class should randomize it anyway.

Anyway, it was just in case you are curious and I'm fine with the current implementation. Let me know when you want me to merge the code.

**Comment by moodmosaic** [comment]
> Just in case you are curious, my idea was to have something like:
> 
> ```cs 
> new Xeger(new Random(Interlocked.Add(ref RandomSeed, 1)))
> ```

From a thread-safety viewpoint, this looks reasonable. In the context of pseudorandom number generators, this must be sampled in order to make sure it'll produce output that is uniformly distributed random and [birthday paradox](https://en.wikipedia.org/wiki/Birthday_problem)-free, at the very least.

**Comment by MagnusMikkelsen** [comment]
Given @moodmosaic comment, shouldn't we just merge it as is @zvirja ?

**Comment by zvirja** [comment]
@moodmosaic The same should be said about the current approach, shouldn't it? 😉 If none of the approaches was tested to prove the statistical quality of the resulting random sequence, we could just ignore this aspect, assuming that both approaches are equal. And with that we could solely focus on performance aspect.

Anyway, merging the code! Thanks again @MagnusMikkelsen for your help!

**Comment by moodmosaic** [comment]
Yeah, but at least right we're following the 'pattern' so we're at least consistent.

**Comment by zvirja** [comment]
@aivascu I suggest to drop a new release, so the fix could be consumed. Let me know if you need my assistance on this ;-)

**Comment by moodmosaic** [comment]
>I suggest to drop a new release, so the fix could be consumed

:+1: :confetti_ball: :rocket: 

---

Thanks @MagnusMikkelsen for your work and @zvirja for the great feedback :beers:

**Comment by aivascu** [comment]
@zvirja the release 4.13.0 has been deployed
